#!/usr/bin/env python3

# TODO

import os
import sys

from analyzer import Analyzer
from termcolor import colored
import helpers

def main():
    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")
        
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    
    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    # get tweets
    tweets = helpers.get_user_timeline(sys.argv[1],50)
    # ensure if it exists
    if tweets == None:
        sys.exit("Doesn’t exist or a screen name’s tweets are private")
    
    # analyze each word in tweets
    for word in tweets:
        score = analyzer.analyze(word)
        if score > 0.0:
            print(colored("{} {}".format(score,word), "green"))
        elif score < 0.0:
            print(colored("{} {}".format(score,word), "red"))
        else:
            print(colored("{} {}".format(score,word), "yellow"))

if __name__ == "__main__":
    main()